### ISSUE TITLE
aimeos/aimeos-core/admin

### ISSUE THREAD

**Issue by 1f7** [aimeos/aimeos-slim#2]
from install:
cp -r vendor/aimeos/aimeos-core/client/html/themes/\* public/aimeos/themes/
cp -r vendor/aimeos/aimeos-core/admin/jqadm/themes/\* public/aimeos/themes/
cp -r vendor/aimeos/aimeos-core/admin/extjs/lib/\* public/aimeos/extjs/lib/
cp -r vendor/aimeos/aimeos-core/admin/extjs/lib/\* public/aimeos/admin/extjs/lib/

Client present, but where is admin folder?

**Comment by aimeos** [comment]
We are currently in the process of splitting up the core library and moving some parts to new extensions. The composer.json file of the aimeos-slim package has been updated to use the 2016.04 branch until we are done with the reorganization in the core.

Please execute the `composer update` command to get the stable 2016.04 core version. Then everything you need should be there like described in the documentation.

**Comment by 1f7** [comment]
Fixed.
All setup steps finished, but [route error](https://github.com/aimeos/aimeos-slim/issues/4)
