### ISSUE TITLE
fill db bug

### ISSUE THREAD

**Issue by 1f7** [aimeos/aimeos-slim#3]
`php vendor/aimeos/aimeos-core/setup.php --config=src/aimeos-settings.php --option=setup/default/demo:1`

Caught PHP error while processing setup:

```
" failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"mshop_locale_site" (
        -- unique site id
        "id" INTEGER NOT NULL AUTO_INCREMENT,
' at line 1
```

```
mysql -V
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
```

**Comment by aimeos** [comment]
Can you please execute `composer update` and use this command to create the database afterwards:

`php vendor/aimeos/aimeos-core/setup.php --config=vendor/aimeos/aimeos-slim/src/aimeos-default.php --config=src/aimeos-settings.php --option=setup/default/demo:1`

After the split of the configuration files, you need to specify the default one too and before your aimeos-setting.php file.

**Comment by 1f7** [comment]
Thank you very much, 
problem solved,  continue explore
Last string:

```
Processing service demo data                                          added
Setup process took 91.138936 sec
```
