### ISSUE TITLE
Can't get the admin URL to work

### ISSUE THREAD

**Issue by codingarrow** [aimeos/aimeos-slim#6]
Hi I was evaluating slim's functionality in one complete application, I have several web projects (CI, Magento, etc.) all on htdocs and I am using xampp

I followed the instruction on the readme, I was able to install the database, and setup httpd.conf to point my aimeos-slim

```
# virtual host being defined.
#
<VirtualHost *:80>
DocumentRoot "C:/xampp/htdocs/aimeos/public"
ServerName slimtest.dev
ServerAlias www.slimtest.dev
<Directory "c:/xampp/htdocs/aimeos/public">
AllowOverride All
Require all Granted
</Directory>
</VirtualHost>
```

I even followed the pertinents setup(s) here https://github.com/slimphp/Slim/issues/2294

```
I can't get the admin to work http://www.slimtest.dev/admin/
Page Not Found

The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.
Visit the Home Page

but the http://www.slimtest.dev/detail/5/Demo_bundle_article/2  works fine !
```

**Comment by aimeos** [comment]
Strange! Is there something in the XAMPP setup or in the `.htaccess` that affects /admin URLs?
Which versions (PHP, Slim, Aimeos) do you use?

BTW: The Slim PHP framework is best for prototyping or if you need a very stripped down framework. If you need a full featured application incl. user management, Laravel would be the better choice.
